import React from 'react';
import { Info } from 'lucide-react';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '../../components/ui/tooltip';
import { PoolInfoProps } from '../../types/pool';

export const PoolInfo = React.memo(({ apy, lastUpdated }: PoolInfoProps) => {
  return (
    <div className="bg-white/5 border border-white/10 rounded-2xl pl-6 pr-6 pt-4 pb-4 flex flex-col md:flex-row md:items-start md:justify-between gap-8">
      <div className="flex-1">
        <h1 className="text-[30px] font-semibold text-primary mb-4">BLP Pool</h1>
        <div className="text-xs text-white/90 mb-4">
          <span className="font-bold text-primary">The Baskt Liquidity Provider (BLP) Pool</span> is
          a liquidity pool where it acts as a counterparty to traders — when traders seek to open
          leverage positions, they borrow tokens from the pool.
        </div>
        <div className="text-white/80 text-xs mb-4">
          <span className="font-bold text-primary">The BLP token</span> is the liquidity provider
          token where its value is derived from:
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>An index fund of USDC, SOL, ETH, WBTC, USDT.</li>
            <li>Earn a share of trading fees and protocol growth.</li>
            <li>
              75% of the generated fees from trading activities are distributed to BLP holders.
            </li>
          </ul>
        </div>
        <div className="text-white/80 text-xs mb-4">
          <span className="font-bold text-primary">The APY</span>, denominated in USD, is calculated
          based on 75% of fees generated from trading activities, which does not include asset
          appreciation and traders' PnL. The generated fees are distributed back to holders by
          redepositing the fees into the pool hourly.
        </div>
      </div>
      <div className="flex flex-col items-end min-w-[180px] justify-start">
        <div className="flex items-center gap-2 text-primary text-xs font-bold mb-1">
          APY
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="inline-block align-middle cursor-pointer">
                  <Info className="h-4 w-4 text-primary" />
                </span>
              </TooltipTrigger>
              <TooltipContent
                side="top"
                className="max-w-xs text-xs text-white bg-[#23263a] border border-white/10"
              >
                APR/APY is updated weekly based on the fees generated by the pool denominated in
                USD.
                <br />
                <br />
                Fees are compounded automatically every hour.
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <span className="text-2xl font-extrabold text-primary">{apy}</span>
        <span className="text-xs text-white/50 mt-1">Last updated at {lastUpdated}</span>
      </div>
    </div>
  );
});

PoolInfo.displayName = 'PoolInfo';
