import React from 'react';
import { Info } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@baskt/ui';
import { PoolInfoProps } from '../../types/pool';

export const PoolInfo = React.memo(({ apy, lastUpdated }: PoolInfoProps) => {
  return (
    <div className="bg-foreground/5 border border-border rounded-2xl pl-6 pr-6 pt-4 pb-4 flex flex-col md:flex-row md:items-start md:justify-between gap-8">
      <div className="flex-1">
        <h1 className="text-[30px] font-semibold text-primary mb-4">BLP Pool</h1>
        <div className="text-xs text-muted-foreground mb-4">
          <span className="font-bold text-primary">The Baskt Liquidity Provider (BLP) Pool</span>{' '}
          acts as a counterparty to traders — when traders seek to open leverage positions, they
          borrow tokens from the pool.
        </div>
      </div>
      <div className="flex flex-col items-end min-w-[180px] justify-start">
        <div className="flex items-center gap-2 text-primary text-xs font-bold mb-1">
          APY
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="inline-block align-middle cursor-pointer">
                  <Info className="h-4 w-4 text-primary" />
                </span>
              </TooltipTrigger>
              <TooltipContent
                side="top"
                className="max-w-xs text-xs text-foreground bg-foreground/5 border border-border"
              >
                APY is updated weekly based on the fees generated by the pool denominated in USD.
                <br />
                <br />
                Fees are compounded automatically every hour.
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <span className="text-2xl font-extrabold text-primary">{apy}</span>
        <span className="text-xs text-muted-foreground mt-1">Last updated at {lastUpdated}</span>
      </div>
    </div>
  );
});

PoolInfo.displayName = 'PoolInfo';
