[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
baskt_v1 = "G4MVhTKu6LGJZ7ZepYA8JonEVVCfH2wuvrJ42MwEthzu"

[registry]
url = "https://stylish-divine-market.solana-mainnet.quiknode.pro/1aec6db0690864cdcaf90a2ba4daf161786b0117/"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "pyth.so"

[test.validator]
bind_address = "127.0.0.1"
url = "https://mainnet.helius-rpc.com/?api-key=afb3963a-b2da-4d38-9f61-9b0588617e74"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "4cSM2e6rvbGQUFiJbqytoVMi5GgghSMr8LwVrT9VPSPo"
