
[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
baskt = "8JaW8fhu46ii83WapMp64i4B4bKTM76XUSXftJfHfLyg"

[registry]
url = "https://stylish-divine-market.solana-mainnet.quiknode.pro/1aec6db0690864cdcaf90a2ba4daf161786b0117/"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "RUSTFLAGS='-C link-arg=-zstack-size=8192' anchor build"
single-test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000"
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
test-ledger = "solana-test-validator --reset --quiet"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://mainnet.helius-rpc.com/?api-key=afb3963a-b2da-4d38-9f61-9b0588617e74"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "usdc-mock.json"
