version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
    container_name: baskt-backend
    ports:
      - "${EXTERNAL_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      # Override the wallet path to point to the mounted location
      - ANCHOR_WALLET=/app/wallet/id.json
    env_file:
      - ../.env
    volumes:
      # Mount the Solana wallet file from host to container
      - "${WALLET_PATH:-/root/.config/solana/id.json}:/app/wallet/id.json:ro"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4000/health').then(r=>r.ok?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - baskt-network

networks:
  baskt-network:
    driver: bridge
