[package]
name = "baskt"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "baskt"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
test = []
anchor-debug = []
serde = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = {version = "0.31.0", features = ["init-if-needed"]}
anchor-spl = "0.31.0"
pyth-solana-receiver-sdk = "0.6.0"
num-traits = "0.2.15"
bytemuck = { version = "1.14.0", features = ["derive"] }
solana-security-txt = "1.1.1"
